apiVersion: v1
kind: Secret
metadata:
  name: minio-cred
type: Opaque
data:
  ID: bWluaW8=
  KEY: bWluaW8xMjM=
  ACCESS_KEY_ID: bWluaW8=
  ACCESS_KEY_KEY: bWluaW8xMjM=
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pv-claim
      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-05-24T17-08-30Z
          imagePullPolicy: IfNotPresent
          args: 
            - server 
            - /data 
          ports:
            - containerPort: 9090
            - containerPort: 9000
          env:
            # - name: MINIO_ACCESS_KEY
            #   value: "minio"
            # - name: MINIO_SECRET_KEY
            #   value: "minio123"
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: minio123
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 30

          resources:
            requests:
              cpu: 400m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: console
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: api
  selector:
    app: minio

---

apiVersion: v1
kind: Pod
metadata:
  name: mc
  namespace: minio
spec:
  volumes:
    - name: mc
      emptyDir: {}
  containers:
    - name: mc
      image: minio/mc:RELEASE.2025-05-21T01-59-54Z
      env:
        - name: MC_HOST_minio
          value: "http://minio:minio123@minio-service:9000"
        - name: MC_URL
          value: "https://minio-service:9000"
        - name: HOME
          value: "/mc"
      volumeMounts:
        - name: mc
          mountPath: "/mc"
      command:
        - "sleep"
        - "3600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always

